name: Deploy to Yandex Cloud Functions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Yandex Cloud CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        
    - name: Configure Yandex Cloud CLI
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
      run: |
        yc config set token $YC_TOKEN
        
    - name: Deploy to Yandex Cloud Functions
      run: |
        yc serverless function version create \
          --function-name=test-function \
          --folder-id=b1ghbomf0b40dknpd5tt
          --runtime python312 \
          --entrypoint index.handler \
          --memory 256Mb \
          --execution-timeout 5s \
          --source-path ./src
